rule create_environment:
    shell:
        """
        mamba env create -f environment.yml --prefix ./.venv
        mamba run -p ./.venv pip install plip
        mamba run -p ./.venv ANARCI --build_models
        """

rule download_stcrdab_summary:
    output: "data/raw/stcrdab_summary.tsv"
    shell: "wget -O {output} https://opig.stats.ox.ac.uk/webapps/stcrdab-stcrpred/summary/all"


rule select_and_process_structures:
    input: "data/raw/stcrdab_summary.tsv"
    output: directory("data/interim/structures")
    resources:
        runtime="20m",
        mem="1GB",
        tasks=1
    script: "scripts/select_and_process_structures.py"
