name: tcr-pmhc-structures
channels:
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - jupyter
  - numpy
  - pandas
  - pip
  - pymol-open-source
  - python=3.11
  - snakemake
  - pip:
    - snakemake-executor-plugin-slurm
    - stcrpy
    - ruff
