name: tcr-pmhc-structures
channels:
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - papermill
  - pip
  - plotly
  - pymol-open-source
  - python=3.11
  - scipy
  - seaborn
  - snakemake
  - pip:
    - kaleido
    - snakemake-executor-plugin-slurm
    - stcrpy
    - ruff
